# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "sinatra", "~> 2.2"
gem 'sinatra-contrib'
gem 'haml-rails'
gem 'webrick'
gem 'capybara'
gem 'poltergeist'
gem 'nokogiri'
gem 'marcel'